### ISSUE TITLE
SignUP Page

### ISSUE THREAD

**Issue by Aisha-Naeem** [Aisha-Naeem/Art-Gallery-Management-System#1]
we have to create the signUp page that looks like or have features like this.
this is just a demo for understanding.

![signup](https://github.com/Aisha-Naeem/Art-Gallery-Management-System/assets/160698499/e4432c22-4b2a-4444-bfe1-342eddf3b379)

![image](https://github.com/Aisha-Naeem/Art-Gallery-Management-System/assets/160698499/7d41edb1-55d7-4f28-995b-4cc8a5d2e169)

**Comment by Aisha-Zahid** [comment]
todo

**Comment by Aisha-Zahid** [comment]
signin
